### ISSUE TITLE
rnode BLE interface crashes rnsd 1.0.3 and 1.0.4

### ISSUE THREAD

**Issue by kujeger** [markqvist/Reticulum#1014]
Hi!

Attempting to start rnsd with a ble rnode configured gives me this error on 1.0.3 and 1.0.4:
```
[2025-11-23 14:00:17] [Error]    The interface "RNode BLE" could not be created. Check your configuration file for errors!
[2025-11-23 14:00:17] [Error]    The contained exception was: 'NoneType' object has no attribute 'lower'
[2025-11-23 14:00:17] [Error]    An unhandled <class 'AttributeError'> exception occurred: 'NoneType' object has no attribute 'lower'
[2025-11-23 14:00:17] [Error]    Traceback (most recent call last):
  File "/home/kujeger/.local/share/uv/tools/rns/lib/python3.12/site-packages/RNS/Reticulum.py", line 763, in __apply_config
    interface = RNodeInterface.RNodeInterface(RNS.Transport, interface_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kujeger/.local/share/uv/tools/rns/lib/python3.12/site-packages/RNS/Interfaces/RNodeInterface.py", line 188, in __init__
    if port.lower().startswith(tcp_uri_scheme):
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

The interface configuration:
```
  [[RNode BLE]]
    type = RNodeInterface
    enabled = yes
    mode = roaming
    port = ble://
    frequency = 869525000
    bandwidth = 125000
    txpower = 17
    spreadingfactor = 8
    codingrate = 5
```

The exact same interface works fine in 1.0.2 (and earlier).

e: this on linux

**Comment by markqvist** [comment]
Never mind, tested locally and works here.

**Comment by markqvist** [comment]
I've uploaded a hotfix release to pip. Could you try to uninstall and reinstall with:

`pip uninstall rns; pip install rns --no-cache-dir`

And let me know if it works for you now?

You should get the `rns-1.0.4-1-py3-none-any.whl` file from pip when downloading it again. If not try a few times until the cache updates.

**Comment by kujeger** [comment]
That was fast, can confirm it works! Thanks!
