### PR TITLE
Ensure Resources have an input_file attribute

### PR DESCRIPTION
**Pull request by Erethon**
After pulling and testing the latest changes in `master`, I ran into an issue when requesting some resources from my node which resulted in the node disconnecting from the testnet. Specifically, rnsd logged:

```
[2024-01-14 22:38:12] [Warning] An interface error occurred for TCPInterface[RNS Testnet Frankfurt/dublin.connect.reticulum.network:4965], the contained exception was: 'Resource' object has no attribute 'input_file'
[2024-01-14 22:38:12] [Warning] Attempting to reconnect... 
```

I believe this was introduced in ae1d962b9ba5915501272e69377766b99feb799d. Making sure that all Resource objects have an `input_file` attribute seems to solve this.

### CODE REVIEW

**Comment by Erethon** [comment]
Seems like this was fixed in a37e03942430df203f3b60581db81dc0dca6646f which wasn't pushed yet when I opened this PR. Closing this then.

**Comment by markqvist** [comment]
Thanks for the effort anyways!
